/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarDetails;
import Business.CarDirectory;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aishwaryasamel
 */
public class AddCarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCarJPanel
     */
    private JPanel userProcessContainer;
    private CarDirectory carDirectory;


    AddCarJPanel(JPanel userProcessContainer, CarDirectory carDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carDirectory = carDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBanner = new javax.swing.JLabel();
        lblSerialId = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        txtSerialId = new javax.swing.JTextField();
        radioYes = new javax.swing.JRadioButton();
        radioNo = new javax.swing.JRadioButton();
        lblMake = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblNoOfSeats = new javax.swing.JLabel();
        txtNoOfSeats = new javax.swing.JTextField();
        lblAttributes = new javax.swing.JLabel();
        txtAttributes = new javax.swing.JTextField();
        lblModelNo = new javax.swing.JLabel();
        txtModelNo = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        lblLastUpdate = new javax.swing.JLabel();
        txtLastUpdate = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblCertExpiryDate = new javax.swing.JLabel();
        txtCertExpiryDate = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblCarName = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        lblRemarks = new javax.swing.JLabel();

        lblBanner.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblBanner.setText("Add Car Details");

        lblSerialId.setText("Serial ID:");

        lblAvailability.setText("Availability:");

        txtSerialId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerialIdKeyReleased(evt);
            }
        });

        radioYes.setText("Yes");
        radioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYesActionPerformed(evt);
            }
        });

        radioNo.setText("No");
        radioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNoActionPerformed(evt);
            }
        });

        lblMake.setText("Make:");

        txtMake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMakeKeyReleased(evt);
            }
        });

        lblYear.setText("Year Of Manufacture:");

        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYearKeyReleased(evt);
            }
        });

        lblNoOfSeats.setText("Number of Seats:");

        txtNoOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfSeatsActionPerformed(evt);
            }
        });
        txtNoOfSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoOfSeatsKeyReleased(evt);
            }
        });

        lblAttributes.setText("Attributes:");

        txtAttributes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAttributesActionPerformed(evt);
            }
        });
        txtAttributes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAttributesKeyReleased(evt);
            }
        });

        lblModelNo.setText("Model Number:");

        txtModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNoActionPerformed(evt);
            }
        });

        lblManufacturer.setText("Manufacturer:");

        txtManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerActionPerformed(evt);
            }
        });
        txtManufacturer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtManufacturerKeyReleased(evt);
            }
        });

        lblLastUpdate.setText("Last Update Date (mm-dd-yyyy):");

        txtLastUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastUpdateActionPerformed(evt);
            }
        });

        lblCity.setText("City:");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });

        lblCertExpiryDate.setText("Certificate Expiration Date( mm-dd-yyyy):");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCarName.setText("Car Name:");

        txtCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSerialId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAvailability)
                                    .addComponent(lblMake)
                                    .addComponent(lblYear)
                                    .addComponent(lblNoOfSeats)
                                    .addComponent(lblAttributes)
                                    .addComponent(lblModelNo)
                                    .addComponent(lblManufacturer)
                                    .addComponent(lblLastUpdate)
                                    .addComponent(lblCity)
                                    .addComponent(lblCertExpiryDate)
                                    .addComponent(lblCarName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnBack)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioNo))
                            .addComponent(txtSerialId, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCarName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCertExpiryDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(radioYes)
                    .addComponent(radioNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNoOfSeats)
                    .addComponent(txtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttributes)
                    .addComponent(txtAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModelNo)
                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastUpdate)
                    .addComponent(txtLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCertExpiryDate)
                    .addComponent(txtCertExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCarName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYesActionPerformed
        if(radioYes.isSelected()){
                radioNo.setSelected(false);
        }     
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYesActionPerformed

    private void radioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNoActionPerformed
        if(radioNo.isSelected()){
                radioYes.setSelected(false);
        }      
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNoActionPerformed

    private void txtNoOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOfSeatsActionPerformed

    private void txtAttributesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttributesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttributesActionPerformed

    private void txtManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerActionPerformed

    private void txtLastUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastUpdateActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try{
            CarDetails carDetails = carDirectory.addCarDetails();
            
            if(radioNo.isSelected()){
                carDetails.setAvailability(radioNo.getText());
            }
            if(radioYes.isSelected()){
                carDetails.setAvailability(radioYes.getText());
            }
            
            carDetails.setSerialID(txtSerialId.getText());
            carDetails.setCarName(txtCarName.getText());
            carDetails.setMake(txtMake.getText());
            carDetails.setYearOfManufacture(Integer.parseInt(txtYear.getText()));
            carDetails.setNumberOfSeats(Integer.parseInt(txtNoOfSeats.getText()));
            carDetails.setAttributes(txtAttributes.getText());
            carDetails.setModelNumber(txtModelNo.getText());
            carDetails.setManufacturer(txtManufacturer.getText());
            carDetails.setCity(txtCity.getText());
            Date certExpiryDate = null;
            Date lastUpdateDate = null;
            lastUpdateDate = new SimpleDateFormat("dd-mm-yyyy").parse(txtLastUpdate.getText());
            certExpiryDate = new SimpleDateFormat("dd-mm-yyyy").parse(txtCertExpiryDate.getText());
            carDetails.setCertExpiryDate(certExpiryDate);
            carDetails.setLastUpdateDate(lastUpdateDate);
           
            JOptionPane.showMessageDialog(null, "Car Details added successfully");
    }//GEN-LAST:event_btnCreateActionPerformed

        catch(ParseException e){
            System.out.println("Check your form");
        }
    }
        // TODO add your handling code here:
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarNameActionPerformed
        String PATTERN = "^[a-zA-Z]{1,15}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtCarName.getText());
        if(!match.matches()){
            lblRemarks.setText("Please enter text for name");   
        }
        else{
            lblRemarks.setText(null); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarNameActionPerformed

    private void txtSerialIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialIdKeyReleased
        String PATTERN = "^[0-9]{1,30}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtSerialId.getText());
        if(!match.matches()){
            lblRemarks.setText("Please enter digits only for Serial ID");   
        }
        else{
            lblRemarks.setText(null); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialIdKeyReleased

    private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
        String PATTERN = "^[a-zA-Z]{1,15}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtCity.getText());
        if(!match.matches()){
            lblRemarks.setText("Please enter text for city");   
        }
        else{
            lblRemarks.setText(null); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityKeyReleased

    private void txtManufacturerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufacturerKeyReleased
        String PATTERN = "^[a-zA-Z]{1,15}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtManufacturer.getText());
        if(!match.matches()){
            lblRemarks.setText("Please enter text for manufacturer");   
        }
        else{
            lblRemarks.setText(null); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerKeyReleased

    private void txtModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNoActionPerformed
        String PATTERN = "^[a-zA-Z0-9]{1,15}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtModelNo.getText());
        if(!match.matches()){
            lblRemarks.setText("Model Number can contain text and digits only");   
        }
        else{
            lblRemarks.setText(null); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNoActionPerformed

    private void txtAttributesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAttributesKeyReleased
        String PATTERN = "^[a-zA-Z,]{1,100}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtAttributes.getText());
        if(!match.matches()){
            lblRemarks.setText("Please enter text only for attributes");   
        }
        else{
            lblRemarks.setText(null); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttributesKeyReleased

    private void txtMakeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMakeKeyReleased
        String PATTERN = "^[a-zA-Z]{1,30}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtMake.getText());
        if(!match.matches()){
            lblRemarks.setText("Please enter text for make");   
        }
        else{
            lblRemarks.setText(null); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakeKeyReleased

    private void txtYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyReleased
        String PATTERN = "^[0-9]{4}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtYear.getText());
        if(!match.matches()){
            lblRemarks.setText("Please enter 4 digits only");   
        }
        else{
            lblRemarks.setText(""); 
        }   
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearKeyReleased

    private void txtNoOfSeatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfSeatsKeyReleased
        String PATTERN = "^[0-9]{1}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtNoOfSeats.getText());
        if(!match.matches()){
            lblRemarks.setText("Please enter a number from 0 to 9");   
        }
        else{
            lblRemarks.setText(""); 
        }   
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOfSeatsKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblAttributes;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCertExpiryDate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblLastUpdate;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblNoOfSeats;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblSerialId;
    private javax.swing.JLabel lblYear;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioYes;
    private javax.swing.JTextField txtAttributes;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCertExpiryDate;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtLastUpdate;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtNoOfSeats;
    private javax.swing.JTextField txtSerialId;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
