/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarDetails;
import Business.CarDirectory;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aishwaryasamel
 */
public class ManageCarDetailsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private CarDirectory carDirectory;
    
    
    /**
     * Creates new form ManageCarDetailsJPanel
     */
    public ManageCarDetailsJPanel(JPanel userProcessContainer,CarDirectory carDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carDirectory = carDirectory;
        populateTable();
    }
    
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblCarDetails.getModel();
        dtm.setRowCount(0);
 
        for (CarDetails carDetails : carDirectory.getCarDetails()){
            Object[] row = new Object[12];
            row[0] = carDetails;
            row[1] = carDetails.getMake();
            row[2] = carDetails.getAvailability();
            row[3] = carDetails.getYearOfManufacture();
            row[4] = carDetails.getNumberOfSeats();
            row[5] = carDetails.getAttributes();
            row[6] = carDetails.getModelNumber();
            row[7] = carDetails.getManufacturer();
            row[8] = carDetails.getLastUpdateDate();
            row[9] = carDetails.getCity();
            row[10] = carDetails.getCertExpiryDate();
            row[11] = carDetails.getSerialID();
            
            dtm.addRow(row);
        } 
          
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFindAvblCar = new javax.swing.JTextField();
        btnSearchModelNo = new javax.swing.JButton();
        btnSearchSerialNo = new javax.swing.JButton();
        txtSearchSerialNo = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarDetails = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCarListMake = new javax.swing.JButton();
        btnSearchByYear = new javax.swing.JButton();
        btnSearchByManu = new javax.swing.JButton();
        btnSearchByCity = new javax.swing.JButton();
        txtCatalogUpdateDate = new javax.swing.JTextField();
        btnExpiryDateCert = new javax.swing.JButton();
        btnSearchCars = new javax.swing.JButton();
        btnFindAvblCar = new javax.swing.JButton();
        btnCheckAvailability = new javax.swing.JButton();
        btnCatalogUpdateDate = new javax.swing.JButton();

        btnSearchModelNo.setBackground(new java.awt.Color(153, 255, 204));
        btnSearchModelNo.setText("Search by Model Number");
        btnSearchModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchModelNoActionPerformed(evt);
            }
        });

        btnSearchSerialNo.setBackground(new java.awt.Color(204, 255, 255));
        btnSearchSerialNo.setText("Search by Serial Number");
        btnSearchSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSerialNoActionPerformed(evt);
            }
        });

        txtSearchSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSerialNoActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 102, 255));
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblCarDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Name", "Make", "Availability", "Year Of Manufacture", "No of Seats", "Attributes", "Model No", "Manufacturer", "Last Update:", "City", "Cert Expiry Date", "Serial Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarDetails);
        if (tblCarDetails.getColumnModel().getColumnCount() > 0) {
            tblCarDetails.getColumnModel().getColumn(0).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(1).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(2).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(3).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(4).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(5).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(6).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(7).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(8).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(9).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(10).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(11).setResizable(false);
        }

        btnDelete.setBackground(new java.awt.Color(204, 102, 255));
        btnDelete.setForeground(new java.awt.Color(0, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(204, 102, 255));
        btnView.setForeground(new java.awt.Color(0, 51, 51));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnCarListMake.setBackground(new java.awt.Color(153, 255, 204));
        btnCarListMake.setText("Search By Make");
        btnCarListMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarListMakeActionPerformed(evt);
            }
        });

        btnSearchByYear.setBackground(new java.awt.Color(153, 255, 204));
        btnSearchByYear.setText("Search By Year");
        btnSearchByYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByYearActionPerformed(evt);
            }
        });

        btnSearchByManu.setBackground(new java.awt.Color(153, 255, 204));
        btnSearchByManu.setText("Search By Manufacturer");
        btnSearchByManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByManuActionPerformed(evt);
            }
        });

        btnSearchByCity.setBackground(new java.awt.Color(153, 255, 204));
        btnSearchByCity.setText("Search By City");
        btnSearchByCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByCityActionPerformed(evt);
            }
        });

        txtCatalogUpdateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatalogUpdateDateActionPerformed(evt);
            }
        });

        btnExpiryDateCert.setBackground(new java.awt.Color(153, 255, 204));
        btnExpiryDateCert.setText("Check Maintenance Certificate Expiry");
        btnExpiryDateCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiryDateCertActionPerformed(evt);
            }
        });

        btnSearchCars.setBackground(new java.awt.Color(153, 255, 204));
        btnSearchCars.setText("Search based on Number of Seats");
        btnSearchCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarsActionPerformed(evt);
            }
        });

        btnFindAvblCar.setBackground(new java.awt.Color(204, 255, 255));
        btnFindAvblCar.setText("Send First Available Car");
        btnFindAvblCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindAvblCarActionPerformed(evt);
            }
        });

        btnCheckAvailability.setBackground(new java.awt.Color(153, 255, 204));
        btnCheckAvailability.setText("Check Availability");
        btnCheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAvailabilityActionPerformed(evt);
            }
        });

        btnCatalogUpdateDate.setBackground(new java.awt.Color(204, 255, 255));
        btnCatalogUpdateDate.setText("Update Fleet Catalog");
        btnCatalogUpdateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogUpdateDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnCheckAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExpiryDateCert, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarListMake, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchByManu, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchByYear, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchCars, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchByCity, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCatalogUpdateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFindAvblCar)
                            .addComponent(btnSearchSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFindAvblCar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCatalogUpdateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCarListMake, btnCheckAvailability, btnExpiryDateCert, btnSearchByCity, btnSearchByManu, btnSearchByYear, btnSearchCars, btnSearchModelNo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCatalogUpdateDate, btnFindAvblCar, btnSearchSerialNo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindAvblCar)
                    .addComponent(txtFindAvblCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchSerialNo)
                    .addComponent(txtSearchSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatalogUpdateDate)
                    .addComponent(txtCatalogUpdateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnCheckAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExpiryDateCert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarListMake)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchByManu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchByYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchByCity)
                .addContainerGap(578, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCarListMake, btnCheckAvailability, btnExpiryDateCert, btnSearchByCity, btnSearchByManu, btnSearchByYear, btnSearchCars, btnSearchModelNo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCatalogUpdateDate, btnFindAvblCar, btnSearchSerialNo});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSerialNoActionPerformed
        CarDetails result = carDirectory.searchByID(txtSearchSerialNo.getText());
        if (result == null){
            JOptionPane.showMessageDialog(null, txtSearchSerialNo.getText(),"Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            ViewCarJPanel panel = new ViewCarJPanel(userProcessContainer,result);
            userProcessContainer.add("ViewCarJPanel",panel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSerialNoActionPerformed

    private void btnSearchModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchModelNoActionPerformed
        
        SearchByModelNoJPanel panel = new SearchByModelNoJPanel(userProcessContainer,carDirectory);
        userProcessContainer.add("SearchByModelNoJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchModelNoActionPerformed

    private void txtSearchSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSerialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSerialNoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblCarDetails.getSelectedRow();
        if(selectedRow >0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the row?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                CarDetails carDetails = (CarDetails) tblCarDetails.getValueAt(selectedRow, 0);
                carDirectory.deleteCarDetails(carDetails);
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select row first","Warning",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
    int selectedRow = tblCarDetails.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select row first","Warning",JOptionPane.WARNING_MESSAGE);
            }
        
        else{
            CarDetails carDetails = (CarDetails) tblCarDetails.getValueAt(selectedRow, 0);
            ViewCarJPanel panel = new ViewCarJPanel(userProcessContainer,carDetails);
            userProcessContainer.add("ViewCarJPanel",panel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCarListMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarListMakeActionPerformed
        SearchByMakeJPanel panel = new SearchByMakeJPanel(userProcessContainer,carDirectory);
        userProcessContainer.add("DisplayDetailsJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarListMakeActionPerformed

    private void btnExpiryDateCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiryDateCertActionPerformed
        
        SearchByExpMCJPanel panel = new SearchByExpMCJPanel(userProcessContainer,carDirectory);
        userProcessContainer.add("ExpiredMCJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExpiryDateCertActionPerformed

    private void btnSearchByCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByCityActionPerformed
        
        SearchByCityJPanel panel = new SearchByCityJPanel(userProcessContainer,carDirectory);
        userProcessContainer.add("SearchByCityJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchByCityActionPerformed

    private void btnSearchByManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByManuActionPerformed
        SearchByManuJPanel panel = new SearchByManuJPanel(userProcessContainer,carDirectory);
        userProcessContainer.add("SearchByManuJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchByManuActionPerformed

    private void btnSearchByYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByYearActionPerformed

        SearchByYearJPanel panel = new SearchByYearJPanel(userProcessContainer,carDirectory);
        userProcessContainer.add("SearchByYearJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
               
    }//GEN-LAST:event_btnSearchByYearActionPerformed
    
    
    private void btnSearchCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarsActionPerformed
        
        SearchBySeatsJPanel panel = new SearchBySeatsJPanel(userProcessContainer,carDirectory);
        userProcessContainer.add("SearchBySeatsJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchCarsActionPerformed

    private void btnFindAvblCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindAvblCarActionPerformed
        String result = carDirectory.findAvailableCar();
        if (result == null){
            JOptionPane.showMessageDialog(null, "Model Number does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            txtFindAvblCar.setText(result);
            //JOptionPane.showMessageDialog(null, result);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindAvblCarActionPerformed

    private void btnCheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAvailabilityActionPerformed
        
        SearchByAvailabilityJPanel panel = new SearchByAvailabilityJPanel(userProcessContainer,carDirectory);
        userProcessContainer.add("SearchByAvailabilityJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);   
//    ArrayList result = carDirectory.checkAvailability();
//        if (result == null){
//            JOptionPane.showMessageDialog(null, "no data available","Information",JOptionPane.INFORMATION_MESSAGE);
//        }
//        else{
//            String arr[] = new String[2];
//            for(int i = 0;i<result.size();i++){
//             arr[i] = result.get(i).toString();
//          
//            }
//            txtCarsAvailable.setText(arr[0]);
//            txtCarsUnavailable.setText(arr[1]);
//            //JOptionPane.showMessageDialog(null, result);
//        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckAvailabilityActionPerformed

    private void btnCatalogUpdateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogUpdateDateActionPerformed
        String result = carDirectory.getUpdateDate();
        if (result == null){
            JOptionPane.showMessageDialog(null, "update date does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
             txtCatalogUpdateDate.setText("Fleet catalog last updated on  "+ result);
            //JOptionPane.showMessageDialog(null, result);
        }
    }//GEN-LAST:event_btnCatalogUpdateDateActionPerformed

    private void txtCatalogUpdateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatalogUpdateDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatalogUpdateDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCarListMake;
    private javax.swing.JButton btnCatalogUpdateDate;
    private javax.swing.JButton btnCheckAvailability;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExpiryDateCert;
    private javax.swing.JButton btnFindAvblCar;
    private javax.swing.JButton btnSearchByCity;
    private javax.swing.JButton btnSearchByManu;
    private javax.swing.JButton btnSearchByYear;
    private javax.swing.JButton btnSearchCars;
    private javax.swing.JButton btnSearchModelNo;
    private javax.swing.JButton btnSearchSerialNo;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarDetails;
    private javax.swing.JTextField txtCatalogUpdateDate;
    private javax.swing.JTextField txtFindAvblCar;
    private javax.swing.JTextField txtSearchSerialNo;
    // End of variables declaration//GEN-END:variables
}
