/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Login;

import UserInterface.Flight.ManageFlightsJPanel;
import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import UserInterface.Fleet.ManageFleetJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rishab
 */
public class LoginAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginAirlinerJPanel
     */
    
    JPanel rightPanel;
    AirlinerDirectory airDir;
    
    public LoginAirlinerJPanel(JPanel rightPanel, AirlinerDirectory airDir) {
        this.rightPanel = rightPanel;
        this.airDir = airDir;
        initComponents();
                populateComboBox();
    }
    
    private void populateComboBox()
    {
       airlinerComboBox.removeAllItems();
       for(Airliner a : airDir.getAirlinerDirectory())
       {
           airlinerComboBox.addItem(a);
       } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        airlinerComboBox = new javax.swing.JComboBox();
        goBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Airliner Login");

        jLabel2.setText("Select Airliner:");

        airlinerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        goBtn.setText("Next");
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goBtn)
                    .addComponent(airlinerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(airlinerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(goBtn)
                .addContainerGap(363, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        // TODO add your handling code here:
        
        Airliner airliner = (Airliner) airlinerComboBox.getSelectedItem();
        ManageFleetJPanel manageFleetPanel = new ManageFleetJPanel(rightPanel, airliner);
        rightPanel.add("ManageFleetJPanel",manageFleetPanel );
        CardLayout cardlayout = (CardLayout)rightPanel.getLayout();
        cardlayout.next(rightPanel);
    }//GEN-LAST:event_goBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox airlinerComboBox;
    private javax.swing.JButton goBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
