/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner.AirlinerDirectory;
import Business.Customer.CustomerDirectory;
import Business.Flights.FlightsDirectory;
import Business.Helper;
import UserInterface.Customer.ManageCustomerJPanel;
import UserInterface.ManageAirliners.ManageAirlinersJPanel;
import UserInterface.Login.LoginAirlinerJPanel;
import UserInterface.Login.LoginFleetJPanel;
import UserInterface.Flight.MasterFlightScheduleJPanel;
import UserInterface.Search.SearchFlightDetailsJPanel;
import java.awt.CardLayout;

/**
 *
 * @author Sriram
 */
public class TravelAgencyFrame extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyFrame
     */
    private AirlinerDirectory airlinerDir;
    private Helper helper;
    private CustomerDirectory cusDir;
    private FlightsDirectory flightDir;

    public AirlinerDirectory getAirlinerDir() {
        return airlinerDir;
    }

    public void setAirlinerDir(AirlinerDirectory airlinerDir) {
        this.airlinerDir = airlinerDir;
    }

    public CustomerDirectory getCusDir() {
        return cusDir;
    }

    public void setCusDir(CustomerDirectory cusDir) {
        this.cusDir = cusDir;
    }
    
    public TravelAgencyFrame() {
        this.airlinerDir = new AirlinerDirectory();
        this.cusDir = new CustomerDirectory();
        this.helper = new Helper();
        airlinerDir.setCustomerDirectory(cusDir);
        this.flightDir = new FlightsDirectory();
        helper.setCustomerDirectory(cusDir);
        helper.setAirlinerDirectory(airlinerDir);
        helper.setFlightsDirectory(flightDir);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        manageAirlinersBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        manageFleetBtn = new javax.swing.JButton();
        manageFlightsBtn = new javax.swing.JButton();
        masterFlight = new javax.swing.JButton();
        bookFlightBtn = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        manageAirlinersBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageAirlinersBtn.setText("Manage Airliners");
        manageAirlinersBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, java.awt.Color.lightGray));
        manageAirlinersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlinersBtnActionPerformed(evt);
            }
        });

        customerBtn.setBackground(new java.awt.Color(153, 153, 153));
        customerBtn.setText("Manage Customers");
        customerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.darkGray));
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SRA Travel Agency");

        manageFleetBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageFleetBtn.setText("Manage Fleet");
        manageFleetBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.darkGray));
        manageFleetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFleetBtnActionPerformed(evt);
            }
        });

        manageFlightsBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageFlightsBtn.setText("Manage Flights");
        manageFlightsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.darkGray));
        manageFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFlightsBtnActionPerformed(evt);
            }
        });

        masterFlight.setBackground(new java.awt.Color(153, 153, 153));
        masterFlight.setText("Master Flight Schedule");
        masterFlight.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.darkGray));
        masterFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterFlightActionPerformed(evt);
            }
        });

        bookFlightBtn.setBackground(new java.awt.Color(153, 153, 255));
        bookFlightBtn.setText("Book Flight");
        bookFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageAirlinersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(manageFleetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageFlightsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(masterFlight)
                .addGap(34, 34, 34)
                .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(bookFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageFleetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageFlightsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masterFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageAirlinersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void manageAirlinersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlinersBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        ManageAirlinersJPanel maPanel = new ManageAirlinersJPanel(rightPanel, airlinerDir, helper);
        rightPanel.add("ManageAirlinersJPanel",maPanel);
        CardLayout cardlayout = (CardLayout)rightPanel.getLayout();
        cardlayout.next(rightPanel);
    }//GEN-LAST:event_manageAirlinersBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        ManageCustomerJPanel mcPanel = new ManageCustomerJPanel(rightPanel, cusDir, helper);
        rightPanel.add("ManageCustomerJPanel",mcPanel);
        CardLayout cardlayout = (CardLayout)rightPanel.getLayout();
        cardlayout.next(rightPanel);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void manageFleetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFleetBtnActionPerformed
        // TODO add your handling code here:
       rightPanel.remove(this);
        LoginAirlinerJPanel laPanel = new LoginAirlinerJPanel(rightPanel, airlinerDir);
        rightPanel.add("LoginAirlinerJPanel",laPanel);
        CardLayout cardlayout = (CardLayout)rightPanel.getLayout();
        cardlayout.next(rightPanel);
    }//GEN-LAST:event_manageFleetBtnActionPerformed

    private void manageFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFlightsBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        LoginFleetJPanel lfPanel = new LoginFleetJPanel(rightPanel, airlinerDir);
        rightPanel.add("LoginFleetJPanel",lfPanel);
        CardLayout cardlayout = (CardLayout)rightPanel.getLayout();
        cardlayout.next(rightPanel);
    }//GEN-LAST:event_manageFlightsBtnActionPerformed

    private void masterFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterFlightActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        MasterFlightScheduleJPanel mfsPanel = new MasterFlightScheduleJPanel(rightPanel, airlinerDir);
        rightPanel.add("MasterFlightScheduleJPanel",mfsPanel);
        CardLayout cardlayout = (CardLayout)rightPanel.getLayout();
        cardlayout.next(rightPanel);
    }//GEN-LAST:event_masterFlightActionPerformed

    private void bookFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightBtnActionPerformed
        // TODO add your handling code here:
        
        SearchFlightDetailsJPanel sfdPanel = new SearchFlightDetailsJPanel(rightPanel, airlinerDir);
        rightPanel.add("SearchFlightDetailsJPanel",sfdPanel);
        CardLayout cardlayout = (CardLayout)rightPanel.getLayout();
        cardlayout.next(rightPanel);    
    }//GEN-LAST:event_bookFlightBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookFlightBtn;
    private javax.swing.JButton customerBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton manageAirlinersBtn;
    private javax.swing.JButton manageFleetBtn;
    private javax.swing.JButton manageFlightsBtn;
    private javax.swing.JButton masterFlight;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
