/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Search;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Flights.Flights;
import Business.Helper;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rishab
 */
public class ConfirmBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmBookingJPanel
     * 
     */
    
    JPanel rightPanel;
    public String seatType;
    private String[][] availableSeats;
    private CustomerDirectory cusDir;
    private Airliner airliner;
    private AirlinerDirectory airlinerDir;
    private Flights flight;
    
    public ConfirmBookingJPanel(JPanel rightPanel, String seatType,Flights flight, Airliner airliner, AirlinerDirectory airlinerDir) {
        this.rightPanel = rightPanel;
        this.seatType = seatType;
        this.flight = flight;
        this.airliner = airliner;
        this.airlinerDir = airlinerDir;
        this.availableSeats = flight.getSeatDirectory().getSeats();
        initComponents();
        populateCustomerIdComboBox();
        populateSeatComboBox(seatType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateCustomerIdComboBox()
    {
        customerIdComboBox.removeAllItems();
        customerIdComboBox.addItem(" ");
        for(Customer c: airlinerDir.getCustomerDirectory().getCustomerDirectory()){
            customerIdComboBox.addItem(c);
        }
    }
    
    public void populateSeatComboBox(String Seat)
    {
        selectSeatComboBox.removeAllItems();
        selectSeatComboBox.addItem(" ");
        if(Seat == "Window")
        {
        selectSeatComboBox.removeAllItems();
        for(int i=0;i<25;i++)
        {
            for(int j=0; j<6; j++)
            {
                if(j==0 || j==5)
                    selectSeatComboBox.addItem(this.availableSeats[i][j]);
            }
        }        
        }
        if(Seat == "Aisle")
        {
         for(int i=0;i<25;i++)
        {
            for(int j=0; j<6; j++)
            {
                if(j==2 || j==3)
                    selectSeatComboBox.addItem(this.availableSeats[i][j]);
            }
        } 
        }
        if(Seat == "Middle")
        {
         for(int i=0;i<25;i++)
        {
            for(int j=0; j<6; j++)
            {
                if(j==1 || j==4)
                    selectSeatComboBox.addItem(this.availableSeats[i][j]);
            }
        } 
        }
    }
    
    private void modifySeatComboBox()
    {
            String selectedSeat = String.valueOf(selectSeatComboBox.getSelectedItem());
                String[][] alteredArray = flight.getSeatDirectory().reserveSeat(selectedSeat);

                selectSeatComboBox.removeAllItems();
                for(int i=0;i<25;i++)
                {
                    for(int j=0; j<6; j++)
                    {
                            selectSeatComboBox.addItem(alteredArray[i][j]);
                    }
                }
    }
    
    private void modifyCustomerTable()
    {
        Customer c = (Customer) customerIdComboBox.getSelectedItem();
        c.setAirliner(airliner.toString());
        c.setSeat(selectSeatComboBox.getSelectedItem().toString());
        c.setFlightID(flight.toString());
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerIdComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        customerAddressTextField = new javax.swing.JTextField();
        mobileNumberTextField = new javax.swing.JTextField();
        details = new javax.swing.JButton();
        selectSeatComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        confirmBtn.setBackground(new java.awt.Color(102, 102, 255));
        confirmBtn.setText("Confirm");
        confirmBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Seat:");

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Flight");

        jLabel3.setText("Select Customer ID: ");

        customerIdComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Customer Details:");

        jLabel5.setText("Customer Name:");

        jLabel6.setText("Customer Address:");

        jLabel7.setText("Mobile Number:");

        customerNameTextField.setEditable(false);
        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        customerAddressTextField.setEditable(false);

        mobileNumberTextField.setEditable(false);

        details.setText("Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });

        selectSeatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel8.setText(this.seatType+" Seats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectSeatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mobileNumberTextField)
                            .addComponent(customerIdComboBox, 0, 173, Short.MAX_VALUE)
                            .addComponent(customerNameTextField)
                            .addComponent(customerAddressTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(409, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(538, 538, 538))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(details))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(customerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mobileNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectSeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        if(customerIdComboBox.getSelectedItem() == " ")
            {
                JOptionPane.showMessageDialog(this, "Please select a customer.");
            }
        if(customerIdComboBox.getSelectedItem() == " ")
            {
                JOptionPane.showMessageDialog(this, "Please select a seat.");
            }
        else
        {
            String selectedSeat = String.valueOf(selectSeatComboBox.getSelectedItem());
            if(selectedSeat.contains("Not Available"))
            {
                  JOptionPane.showMessageDialog(this, "Seat not available.");
                  return;
            }
            else{
                 int input = JOptionPane.showConfirmDialog(null, 
                "Do you want to confirm the booking?", "Select an Option...",JOptionPane.YES_NO_CANCEL_OPTION);
                if(input == 0)
                {
                JOptionPane.showMessageDialog(this, "Booking Confirmed");
                }
            modifyCustomerTable();
            modifySeatComboBox();
            }         
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
//              rightPanel.remove(this);
              CardLayout cardLayout = (CardLayout)rightPanel.getLayout();
              cardLayout.previous(rightPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        // TODO add your handling code here:
        try{
        Customer c = (Customer) customerIdComboBox.getSelectedItem();
        customerNameTextField.setText(c.getCustomerName());
        customerAddressTextField.setText(c.getCustomerAddress());
        mobileNumberTextField.setText(String.valueOf(c.getMobileNumber()));
        }
        catch(ClassCastException e)
        {
            JOptionPane.showMessageDialog(this, "Please select a customer.");
            return;
        }
    }//GEN-LAST:event_detailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField customerAddressTextField;
    private javax.swing.JComboBox customerIdComboBox;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JButton details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mobileNumberTextField;
    private javax.swing.JComboBox selectSeatComboBox;
    // End of variables declaration//GEN-END:variables
}
