/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Search;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Fleet.FleetDirectory;
import Business.Flights.Flights;
import Business.Flights.FlightsDirectory;
import Business.Helper;
import UserInterface.Search.AvailableFlightsJPanel;
import java.awt.CardLayout;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rishab
 */
public class SearchFlightDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchFlightDetailsJPanel
     */
    
    private JPanel rightPanel;
    private AirlinerDirectory airlinerDirectory;
    
    public SearchFlightDetailsJPanel(JPanel rightPanel, AirlinerDirectory airlinerDirectory) {
        this.rightPanel = rightPanel;
        this.airlinerDirectory = airlinerDirectory;
        initComponents();
        populateComboBoxes();
    }
    
    private boolean ifAlreadyExists(JComboBox comboBox, String search){
        ComboBoxModel model = comboBox.getModel();
        int size = model.getSize();
        boolean flag = false;
         for(int i=0;i<size;i++)
         {
             String item = String.valueOf(comboBox.getItemAt(i));
             if(item.equalsIgnoreCase(search))
             {
                 flag = true;
                 break;
             }
         }
         return flag;
    }
    
    public void populateComboBoxes(){
        departureComboBox.removeAllItems();
        arrivalComboBox.removeAllItems();
        dateComboBox.removeAllItems();
        timeOfDayComboBox.removeAllItems();
        for(Airliner a : airlinerDirectory.getAirlinerDirectory())
        {
            for(Flights f : a.getFlightsDirectory().getFlightsDirectory())
            {              
            if(!(ifAlreadyExists(departureComboBox, f.getDepartureLocation())))
                departureComboBox.addItem(f.getDepartureLocation());
            if(!(ifAlreadyExists(arrivalComboBox, f.getArrivalLocation())))
                arrivalComboBox.addItem(f.getArrivalLocation());
            if(!(ifAlreadyExists(timeOfDayComboBox, f.getPreferedTimeOfDay())))
                timeOfDayComboBox.addItem(f.getPreferedTimeOfDay());
            if(!(ifAlreadyExists(dateComboBox, f.getDate())))
                dateComboBox.addItem(f.getDate());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        departureComboBox = new javax.swing.JComboBox();
        arrivalComboBox = new javax.swing.JComboBox();
        timeOfDayComboBox = new javax.swing.JComboBox();
        dateComboBox = new javax.swing.JComboBox();
        searchBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        seatTypeComboBox = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flight Details Search");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Departure Location:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Arrival Location:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Time of Day:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Date:");

        departureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        arrivalComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timeOfDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Morning", "Evening", "Night" }));

        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Select Seat Type:");

        seatTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Window", "Aisle", "Middle" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(453, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departureComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(arrivalComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timeOfDayComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(416, 416, 416))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(470, 470, 470))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(arrivalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(timeOfDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(seatTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(searchBtn)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here
        String departure = String.valueOf(departureComboBox.getSelectedItem());
        String arrival = String.valueOf(arrivalComboBox.getSelectedItem());
        String timeOfDay = String.valueOf(timeOfDayComboBox.getSelectedItem());
        String date = String.valueOf(dateComboBox.getSelectedItem());
        
        String[] selections = new String[] {departure, arrival, timeOfDay, date};   
        String seatType = new String();
        seatType = String.valueOf(seatTypeComboBox.getSelectedItem());
        
       /* if(seatType == "Middle")
        {
            JOptionPane.showMessageDialog(this, "Due to the ongoing COVID 19, No middle seats available.");
            return;
        }*/
        
        CardLayout cardlayout = (CardLayout)rightPanel.getLayout();
        AvailableFlightsJPanel availFlightsPanel = new AvailableFlightsJPanel(rightPanel, seatType, selections, airlinerDirectory);
        rightPanel.add("AvailableFlightsJPanel",availFlightsPanel);
        cardlayout.next(rightPanel);
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox arrivalComboBox;
    private javax.swing.JComboBox dateComboBox;
    private javax.swing.JComboBox departureComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox seatTypeComboBox;
    private javax.swing.JComboBox timeOfDayComboBox;
    // End of variables declaration//GEN-END:variables
}
