/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Profile;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author aishwaryasamel
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    //private Profile profile;
    public ViewPanel(Profile profile) {
        //this.profile = profile;
        initComponents();
        displayProfile(profile);
    }
    public void displayProfile(Profile profile) {
        txtName.setText(profile.getName());
        txtGeoData.setText(profile.getGeographicData());
        txtDob.setText(profile.getDateOfBirth());
        txtTeleNo.setText(String.valueOf(profile.getTelephoneNo()));
        txtFaxNo.setText(String.valueOf(profile.getFaxNumber()));
        txtEmailId.setText(profile.getEmailId());
        txtSSN.setText(String.valueOf(profile.getSsn()));
        txtMRN.setText(String.valueOf(profile.getMrn()));
        txtHPBeneNo.setText(String.valueOf(profile.getHpbn()));
        txtAccountNo.setText(String.valueOf(profile.getBankAccountNo()));
        txtLicenseNo.setText(String.valueOf(profile.getLicenseNo()));
        txtVehicleNo.setText(String.valueOf(profile.getVehicleNo()));       
        txtDeviceNo.setText(String.valueOf(profile.getDeviceSerialNo()));
        txtLinkedIn.setText(profile.getLinkedInUrl());
        txtIPAddress.setText(profile.getIpAddress());
        txtFingerprint.setText(profile.getFingerprint());  
        txtUnique.setText(profile.getUniqueId());
        txtImagePath.setText(profile.getImagePath());     
        ImageIcon iconPhoto = new ImageIcon(profile.getImagePath());
        Image imagePhoto = iconPhoto.getImage();
        //.getScaledInstance(lblImage.getWidth(),lblImage.getHeight(),Image.SCALE_SMOOTH);
        lblImage.setIcon(iconPhoto);
        txtFingerprint.setText(profile.getFpPath());     
        ImageIcon iconPrint = new ImageIcon(profile.getFpPath());
        Image imagePrint = iconPrint.getImage();
        //.getScaledInstance(lblImage.getWidth(),lblImage.getHeight(),Image.SCALE_SMOOTH);
        lblFingerprintImg.setIcon(iconPrint);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhoto = new javax.swing.JLabel();
        lblUnique = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        Banner = new javax.swing.JLabel();
        txtTeleNo = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtFaxNo = new javax.swing.JTextField();
        lblGeoData = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtUnique = new javax.swing.JTextField();
        lblTeleNo = new javax.swing.JLabel();
        lblFaxNo = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMRN = new javax.swing.JLabel();
        lblHPBeneNo = new javax.swing.JLabel();
        lblAccountNo = new javax.swing.JLabel();
        lblImagePath = new javax.swing.JLabel();
        lblLicenseNo = new javax.swing.JLabel();
        txtImagePath = new javax.swing.JTextField();
        lblVehicleNo = new javax.swing.JLabel();
        lblDeviceNo = new javax.swing.JLabel();
        txtAccountNo = new javax.swing.JTextField();
        lblLinkedIn = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        txtHPBeneNo = new javax.swing.JTextField();
        txtLicenseNo = new javax.swing.JTextField();
        txtVehicleNo = new javax.swing.JTextField();
        txtDeviceNo = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        lblFingerprintImg = new javax.swing.JLabel();
        txtFingerprint = new javax.swing.JTextField();
        lblFingerprint = new javax.swing.JLabel();

        lblPhoto.setText("Photograph:");

        lblUnique.setText("Unique Identifier:");

        txtName.setEditable(false);

        txtGeoData.setEditable(false);

        txtDob.setEditable(false);

        Banner.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Banner.setForeground(new java.awt.Color(0, 0, 255));
        Banner.setText("View Profile");

        txtTeleNo.setEditable(false);

        lblName.setText("Name:");

        txtFaxNo.setEditable(false);

        lblGeoData.setText("Geographic Data:");

        txtEmailId.setEditable(false);

        lblDob.setText("Date Of Birth(mm/dd/yyyy):");

        txtSSN.setEditable(false);

        txtUnique.setEditable(false);

        lblTeleNo.setText("Telephone No:");

        lblFaxNo.setText("FAX Number:");

        lblEmailId.setText("Email Id:");

        lblSSN.setText("Social Security Number:");

        lblMRN.setText("Medical Record Number:");

        lblHPBeneNo.setText("Health Plan Beneficiary Number:");

        lblAccountNo.setText("Bank Account Number:");

        lblImagePath.setText("Image Path:");

        lblLicenseNo.setText("License Number:");

        txtImagePath.setEditable(false);

        lblVehicleNo.setText("Vehicle Number:");

        lblDeviceNo.setText("Device Serial Number:");

        txtAccountNo.setEditable(false);

        lblLinkedIn.setText("LinkedIn URL:");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N

        lblIPAddress.setText("IP Address:");

        txtMRN.setEditable(false);

        txtHPBeneNo.setEditable(false);

        txtLicenseNo.setEditable(false);

        txtVehicleNo.setEditable(false);

        txtDeviceNo.setEditable(false);

        txtLinkedIn.setEditable(false);

        txtIPAddress.setEditable(false);

        txtFingerprint.setEditable(false);
        txtFingerprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFingerprintActionPerformed(evt);
            }
        });

        lblFingerprint.setText("Fingerprint:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFingerprint)
                    .addComponent(lblUnique))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFingerprintImg, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(196, 196, 196)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblName)
                                        .addComponent(lblGeoData)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIPAddress)
                                    .addComponent(lblLinkedIn)
                                    .addComponent(lblDeviceNo)
                                    .addComponent(lblVehicleNo)
                                    .addComponent(lblLicenseNo)
                                    .addComponent(lblAccountNo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHPBeneNo)
                                        .addComponent(lblMRN, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblEmailId, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblFaxNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTeleNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDob, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtGeoData, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtDob, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtTeleNo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtFaxNo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtMRN, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtHPBeneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtLicenseNo)
                                .addComponent(txtVehicleNo)
                                .addComponent(txtDeviceNo)
                                .addComponent(txtLinkedIn)
                                .addComponent(txtIPAddress)
                                .addComponent(txtAccountNo))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPhoto)
                                    .addGap(15, 15, 15)
                                    .addComponent(lblImage))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblImagePath)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addComponent(Banner)))
                    .addContainerGap(196, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUnique)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFingerprint)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFingerprintImg, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(Banner)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGeoData)
                        .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDob)
                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTeleNo)
                                .addComponent(txtTeleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFaxNo)
                                        .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(lblPhoto)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSSN)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblImage))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMRN)
                        .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHPBeneNo)
                        .addComponent(txtHPBeneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblImagePath)
                        .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAccountNo)
                        .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLicenseNo)
                        .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVehicleNo))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDeviceNo)
                        .addComponent(txtDeviceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLinkedIn)
                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lblIPAddress))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(85, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFingerprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFingerprintActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtFingerprintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JLabel lblAccountNo;
    private javax.swing.JLabel lblDeviceNo;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblFaxNo;
    private javax.swing.JLabel lblFingerprint;
    private javax.swing.JLabel lblFingerprintImg;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHPBeneNo;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTeleNo;
    private javax.swing.JLabel lblUnique;
    private javax.swing.JLabel lblVehicleNo;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtDeviceNo;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtFingerprint;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHPBeneNo;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTeleNo;
    private javax.swing.JTextField txtUnique;
    private javax.swing.JTextField txtVehicleNo;
    // End of variables declaration//GEN-END:variables

    
}
